# Generated by Django 3.0.3 on 2020-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeAssistido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('duração', models.TimeField()),
                ('diretor', models.CharField(max_length=40)),
                ('produtora', models.CharField(max_length=30)),
                ('capa', models.ImageField(upload_to='')),
            ],
        ),
    ]
