# Generated by Django 3.0.3 on 2020-05-14 02:56

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=60, null=True)),
                ('ano', models.IntegerField()),
                ('duração', models.IntegerField()),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('produtora', models.CharField(blank=True, max_length=30, null=True)),
                ('midia', models.CharField(blank=True, max_length=30, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Copie a URL do vídeo e cole acima.')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colecao_filmes.Genero')),
            ],
        ),
    ]
