# Generated by Django 3.0.3 on 2020-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(blank=True, null=True, to='colecao_filmes.Genero'),
        ),
    ]
