# Generated by Django 3.0.3 on 2020-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmeassistido',
            name='midia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filmeassistido',
            name='diretor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='filmeassistido',
            name='genero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filmeassistido',
            name='produtora',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filmeassistido',
            name='titulo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
