# Generated by Django 3.0.3 on 2020-02-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0002_auto_20200211_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmeAssistido',
            new_name='Filme',
        ),
    ]
