# Generated by Django 3.0.3 on 2020-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0002_auto_20200604_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(to='colecao_filmes.Genero'),
        ),
    ]
