# Generated by Django 3.0.3 on 2020-02-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0003_auto_20200216_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='duração',
            field=models.IntegerField(),
        ),
    ]
