# Generated by Django 3.0.3 on 2020-02-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0004_auto_20200216_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='midia',
        ),
    ]
