# Generated by Django 3.0.3 on 2020-02-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0006_filme_midia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='capa',
        ),
    ]
