# Generated by Django 3.0.3 on 2020-07-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0006_auto_20200706_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
