# Generated by Django 3.0.3 on 2020-02-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0007_remove_filme_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='capa',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
