# Generated by Django 3.0.3 on 2020-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0008_filme_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
