# Generated by Django 3.0.3 on 2020-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0009_auto_20200305_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
