# Generated by Django 3.0.3 on 2021-04-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0009_auto_20210330_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
