# Generated by Django 3.0.3 on 2021-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0010_auto_20210331_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagem',
            field=models.ImageField(default='/media/default.jpg', upload_to='profile_pics'),
        ),
    ]
