# Generated by Django 3.0.3 on 2021-04-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0011_auto_20210413_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
