# Generated by Django 3.0.3 on 2020-03-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0013_auto_20200317_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
