# Generated by Django 3.0.3 on 2020-03-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0015_auto_20200317_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
