# Generated by Django 3.0.3 on 2020-03-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0016_auto_20200318_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True, max_length=131, null=True),
        ),
    ]
