# Generated by Django 3.0.3 on 2020-04-22 05:33

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0018_auto_20200331_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
