# Generated by Django 3.0.3 on 2020-04-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0019_filme_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='video',
        ),
    ]
