# Generated by Django 3.0.3 on 2020-04-22 19:23

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colecao_filmes', '0020_remove_filme_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
